<?php
        unset($_SESSION['type']);
        unset($_SESSION['name']);
        unset($_SESSION['email']);
        unset($_SESSION["current_date"]);
        unset($_SESSION["current_day_of_the_week"]);
        session_unset();
        session_destroy();
        header('location:index.php?logged_out');
?>